
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'quantifiedstepleftLBRACKETRBRACKETleftORleftANDleftLPARENRPARENrightNOTleftEQNAME VALUE EQ AND OR LBRACKET RBRACKET LPAREN RPAREN NOT OPTION ATLEASTONE ANYexpression : quantifiedstep expression\n                  | quantifiedstep quantifiedstep : step \n            | OPTION step\n            | ATLEASTONE step \n            | ANY stepstep : atomicconstraint\n            | NOT step\n            | LBRACKET classconstraint RBRACKET classconstraint : classconstraint AND partofclassconstraint\n            | classconstraint OR partofclassconstraint \n            | partofclassconstraint partofclassconstraint : atomicconstraint\n                    | LPAREN classconstraint RPAREN  \n                    | NOT classconstraint atomicconstraint : NAME EQ VALUE '
    
_lr_action_items = {'RBRACKET':([14,17,18,20,22,26,27,28,],[-12,-13,23,-16,-15,-14,-11,-10,]),'ANY':([0,],[1,]),'OR':([14,17,18,20,21,22,26,27,28,],[-12,-13,24,-16,24,-15,-14,-11,-10,]),'LPAREN':([8,15,16,24,25,],[15,15,15,15,15,]),'VALUE':([13,],[20,]),'NOT':([0,1,3,6,8,9,15,16,24,25,],[3,3,3,3,16,3,16,16,16,16,]),'RPAREN':([14,17,20,21,22,26,27,28,],[-12,-13,-16,26,-15,-14,-11,-10,]),'OPTION':([0,],[6,]),'EQ':([7,],[13,]),'AND':([14,17,18,20,21,22,26,27,28,],[-12,-13,25,-16,25,-15,-14,-11,-10,]),'LBRACKET':([0,1,3,6,9,],[8,8,8,8,8,]),'$end':([2,4,5,10,11,12,19,20,23,],[0,-7,-3,-6,-8,-4,-5,-16,-9,]),'ATLEASTONE':([0,],[9,]),'NAME':([0,1,3,6,8,9,15,16,24,25,],[7,7,7,7,7,7,7,7,7,7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'step':([0,1,3,6,9,],[5,10,11,12,19,]),'atomicconstraint':([0,1,3,6,8,9,15,16,24,25,],[4,4,4,4,17,4,17,17,17,17,]),'partofclassconstraint':([8,15,16,24,25,],[14,14,14,27,28,]),'classconstraint':([8,15,16,],[18,21,22,]),'quantifiedstep':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> quantifiedstep","S'",1,None,None,None),
  ('expression -> quantifiedstep expression','expression',2,'p_expression','pyrata_parser.py',63),
  ('expression -> quantifiedstep','expression',1,'p_expression','pyrata_parser.py',64),
  ('quantifiedstep -> step','quantifiedstep',1,'p_quantifiedstep','pyrata_parser.py',146),
  ('quantifiedstep -> OPTION step','quantifiedstep',2,'p_quantifiedstep','pyrata_parser.py',147),
  ('quantifiedstep -> ATLEASTONE step','quantifiedstep',2,'p_quantifiedstep','pyrata_parser.py',148),
  ('quantifiedstep -> ANY step','quantifiedstep',2,'p_quantifiedstep','pyrata_parser.py',149),
  ('step -> atomicconstraint','step',1,'p_step','pyrata_parser.py',397),
  ('step -> NOT step','step',2,'p_step','pyrata_parser.py',398),
  ('step -> LBRACKET classconstraint RBRACKET','step',3,'p_step','pyrata_parser.py',399),
  ('classconstraint -> classconstraint AND partofclassconstraint','classconstraint',3,'p_classconstraint','pyrata_parser.py',443),
  ('classconstraint -> classconstraint OR partofclassconstraint','classconstraint',3,'p_classconstraint','pyrata_parser.py',444),
  ('classconstraint -> partofclassconstraint','classconstraint',1,'p_classconstraint','pyrata_parser.py',445),
  ('partofclassconstraint -> atomicconstraint','partofclassconstraint',1,'p_partofclassconstraint','pyrata_parser.py',475),
  ('partofclassconstraint -> LPAREN classconstraint RPAREN','partofclassconstraint',3,'p_partofclassconstraint','pyrata_parser.py',476),
  ('partofclassconstraint -> NOT classconstraint','partofclassconstraint',2,'p_partofclassconstraint','pyrata_parser.py',477),
  ('atomicconstraint -> NAME EQ VALUE','atomicconstraint',3,'p_atomicconstraint','pyrata_parser.py',497),
]
